### ISSUE TITLE
node_modules

### ISSUE THREAD

**Issue by 3lm0n0** [Emanuelbahia/grupo_2_DigitalArts#1]
no deberia estar la carpeta node_modules.

**Comment by Emanuelbahia** [comment]
ya eliminamos la carpeta nodule_modules.

**Comment by 3lm0n0** [comment]
sigo viendo la carpeta.

**Comment by Emanuelbahia** [comment]
cuando saque elimine la carpeta no podia levantar el servidor!
me daba error nodemon app.js y me decia q no encontraba express.
por eso volvi a agregarla y me andaba todo!
como puedo hacer ?

**Comment by joseamayadh** [comment]
Debes configurar tu archivo .gitignore para que no suban los módulos en el repositorio.

https://www.freecodecamp.org/espanol/news/gitignore-explicado-que-es-y-como-agregar-a-tu-repositorio/#:~:text=gitignore%20%2C%20es%20un%20archivo%20de,puedes%20crear%20un%20archivo%20global%20.

# dependencies
/node_modules

**Comment by Emanuelbahia** [comment]
al .gitignore lo subi con:
node_modules   y 
/node_modules

y me sigue subiendo la carpeta al repo!

**Comment by Emanuelbahia** [comment]
resuelto !!!
