### ISSUE TITLE
No es mobile first

### ISSUE THREAD

**Issue by 3lm0n0** [Emanuelbahia/grupo_2_DigitalArts#2]
Los wireframes para telefono no estan.

**Comment by 3lm0n0** [comment]
.item{
    flex: 1 1 150px; --> las dimensiones son fijas, cuando la pantalla es muy pequeña solo muestra de a 1 imagen.
    padding-left: 3%;
    padding-right: 3%;
 }

**Comment by Emanuelbahia** [comment]
.item{
    flex: 1 1;
    padding-left: 3%;
    padding-right: 3%;
 }
resuelto !
gracias !!
